Update README.md
lbighetti/programando-na-gringa pull request #2
Opened 2018-07-18 10:41 UTC by Morette

Adicionei a CROWD, pois achei interessante a proposta dela de a empresa ir até você.

2018-07-18 16:12 UTC, lbighetti requested changes
Obrigado pelas adições! Mandei umas perguntas aqui dá uma olhada quando puder

2018-07-18 16:12 UTC, lbighetti commented on README.md
> +    - Site para busca de emprego em todo mundo
o .com.br parece ter vagas só do Brasil, certo ?

2018-07-18 16:12 UTC, lbighetti commented on README.md
> +    - Site para buscar freelas, onde você colocar seu portfólio e as empresas te selecionam
Esse site não me parece estar ligado com trabalho no exterior. Será que faz sentido colocarmos nesse repo ?

2018-07-18 16:12 UTC, lbighetti commented on README.md
> +    - Vagas para TI focadas em Portugal
Perfeito, não conhecia esse, thanks !

2018-07-18 16:21 UTC, Morette commented on README.md
> +    - Site para busca de emprego em todo mundo
você tem razão, o indeed é local
tipo indeed portugal é indeed.pt
frança é indeed.fr
alamanha de.indee.com

2018-07-18 16:21 UTC, Morette commented on README.md
> +    - Site para buscar freelas, onde você colocar seu portfólio e as empresas te selecionam
Então, ele é um site BR só que não sei quais as empresas que buscam nele.
Pensei que poderia ter empresas internacionais...

2018-07-19 05:26 UTC, lbighetti approved these changes

2018-07-19 05:27 UTC, lbighetti commented on README.md
> +    - Site para busca de emprego em todo mundo
Se tu quiser colocar o indeed, talvez fazer de uma forma mostrando isso ai que você mostrou, dai acho que faz sentido! O que acha ? anyway vou dar merge dai vc faz outro PR se quiser! 👍

2018-07-19 05:27 UTC, merged